"""
agent/tools/harness_template.py
────────────────────────────────────────────────────────────────────────────
FIXED experiment harness — written by ExperimentRunner into every experiment
folder as train_eval.py.  Never generated by the LLM.

Contract
────────
The LLM provides ONLY model.py, which must define:

    def build_and_train(X_train, y_train, X_val, y_val, class_weights):
        \"\"\"
        Train a model and return the fitted model object.
        The returned object must implement .predict(X) -> np.ndarray.
        \"\"\"
        ...
        return fitted_model

This harness:
  1. Loads train.pkl and val.pkl  (NEVER test.pkl — hardcoded, not configurable)
  2. Applies scaler.pkl + selector.pkl transforms
  3. Loads class_weights.pkl
  4. Calls build_and_train() from the LLM's model.py
  5. Computes all required metrics on the VAL set
  6. Writes results.json — ALWAYS, even on failure (status="failed")

The LLM cannot control file I/O, cannot load the test set, and cannot
skip or alter the results.json write.
"""

# ─────────────────────────────────────────────────────────────────────────────
# This string is the actual Python code that gets written to train_eval.py.
# Use {exp_id}, {architecture}, {architecture_family} as format placeholders.
# ─────────────────────────────────────────────────────────────────────────────

HARNESS_CODE: str = '''#!/usr/bin/env python3
"""
train_eval.py  —  FIXED harness (not LLM-generated)
Experiment: {exp_id}
Architecture: {architecture}
Family: {architecture_family}
"""
import importlib.util
import json
import os
import pickle
import sys
import time
import traceback
from pathlib import Path

import numpy as np
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    confusion_matrix,
)

# ── Resolve project root (works from any cwd) ─────────────────────────────────
_EXP_DIR      = Path(os.environ.get("EXP_DIR", Path(__file__).parent)).resolve()
_PROJECT_ROOT = Path(os.environ.get("PROJECT_ROOT", Path(__file__).parent.parent.parent)).resolve()
sys.path.insert(0, str(_PROJECT_ROOT))

_SPLITS_DIR    = _PROJECT_ROOT / "data" / "splits"
_PROCESSED_DIR = _PROJECT_ROOT / "data" / "processed"

# ── Paths (hardcoded — LLM cannot change these) ───────────────────────────────
_TRAIN_PKL       = _SPLITS_DIR / "train.pkl"
_VAL_PKL         = _SPLITS_DIR / "val.pkl"
# test.pkl is intentionally NOT referenced anywhere in this file.
_SCALER_PKL      = _PROCESSED_DIR / "scaler.pkl"
_SELECTOR_PKL    = _PROCESSED_DIR / "selector.pkl"
_WEIGHTS_PKL     = _PROCESSED_DIR / "class_weights.pkl"
_MODEL_PY        = _EXP_DIR / "model.py"
_RESULTS_JSON    = _EXP_DIR / "results.json"

# ── Metadata (filled by ExperimentRunner template substitution) ───────────────
EXP_ID               = "{exp_id}"
ARCHITECTURE         = "{architecture}"
ARCHITECTURE_FAMILY  = "{architecture_family}"
TIMESTAMP            = "{timestamp}"
HYPERPARAMS: dict    = {hyperparams_json}

print(f"[harness] EXP_DIR      = {{_EXP_DIR}}")
print(f"[harness] PROJECT_ROOT = {{_PROJECT_ROOT}}")
print(f"[harness] Experiment   = {{EXP_ID}}")


def _write_results(result: dict) -> None:
    """Always write results.json, even on failure."""
    _RESULTS_JSON.write_text(
        json.dumps(result, indent=2, default=str), encoding="utf-8"
    )
    print(f"[harness] results.json written -> {{_RESULTS_JSON}}")


def _build_error_result(error_msg: str, train_time: float = 0.0) -> dict:
    return {{
        "exp_id":               EXP_ID,
        "machine_id":           os.environ.get("MACHINE_ID", ""),
        "architecture":         ARCHITECTURE,
        "architecture_family":  ARCHITECTURE_FAMILY,
        "hyperparams":          HYPERPARAMS,
        "timestamp":            TIMESTAMP,
        "val_accuracy":         0.0,
        "val_f1_macro":         0.0,
        "val_f1_per_class":     {{}},
        "val_confusion_matrix": [],
        "train_time_seconds":   round(train_time, 3),
        "model_params_count":   0,
        "status":               "failed",
        "error_message":        error_msg,
    }}


# ── Step 1: Load splits (ONLY train + val — test.pkl never touched) ───────────
print("[harness] Loading train split ...")
try:
    with open(_TRAIN_PKL, "rb") as f:
        d = pickle.load(f)
    X_train_raw = d.get("X", d.get("X_train"))
    y_train     = d.get("y", d.get("y_train"))
    if X_train_raw is None or y_train is None:
        raise KeyError(f"train.pkl keys: {{list(d.keys())}}")
except Exception as exc:
    _write_results(_build_error_result(f"Failed to load train.pkl: {{exc}}"))
    sys.exit(1)

print("[harness] Loading val split ...")
try:
    with open(_VAL_PKL, "rb") as f:
        d = pickle.load(f)
    X_val_raw = d.get("X", d.get("X_val"))
    y_val     = d.get("y", d.get("y_val"))
    if X_val_raw is None or y_val is None:
        raise KeyError(f"val.pkl keys: {{list(d.keys())}}")
except Exception as exc:
    _write_results(_build_error_result(f"Failed to load val.pkl: {{exc}}"))
    sys.exit(1)

print(f"[harness] Train: X={{X_train_raw.shape}}  y={{y_train.shape}}")
print(f"[harness] Val  : X={{X_val_raw.shape}}    y={{y_val.shape}}")

# ── Step 2: Apply scaler + selector (fit on train, transform both) ────────────
print("[harness] Applying scaler + selector ...")
try:
    with open(_SCALER_PKL, "rb") as f:
        scaler = pickle.load(f)
    with open(_SELECTOR_PKL, "rb") as f:
        selector = pickle.load(f)
    X_train = selector.transform(scaler.transform(X_train_raw))
    X_val   = selector.transform(scaler.transform(X_val_raw))
    print(f"[harness] Reduced: train {{X_train.shape}}  val {{X_val.shape}}")
except Exception as exc:
    _write_results(_build_error_result(f"Scaler/selector failed: {{exc}}"))
    sys.exit(1)

# ── Step 3: Load class weights ────────────────────────────────────────────────
print("[harness] Loading class weights ...")
try:
    with open(_WEIGHTS_PKL, "rb") as f:
        class_weights = pickle.load(f)
    print(f"[harness] Class weights: {{class_weights}}")
except Exception as exc:
    print(f"[harness] WARNING: Could not load class weights: {{exc}}")
    # Fall back to balanced weights — still better than ignoring imbalance
    classes = np.unique(y_train)
    counts  = np.bincount(y_train.astype(int))
    total   = len(y_train)
    class_weights = {{int(c): total / (len(classes) * counts[int(c)]) for c in classes}}
    print(f"[harness] Computed fallback weights: {{class_weights}}")

# ── Step 4: Import LLM's build_and_train from model.py ───────────────────────
print(f"[harness] Importing build_and_train from {{_MODEL_PY}} ...")
try:
    spec   = importlib.util.spec_from_file_location("model", _MODEL_PY)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    build_and_train = getattr(module, "build_and_train")
except Exception as exc:
    tb = traceback.format_exc()
    _write_results(_build_error_result(f"Import of model.py failed:\\n{{tb}}"))
    sys.exit(1)

if not callable(build_and_train):
    _write_results(_build_error_result("model.py: build_and_train is not callable"))
    sys.exit(1)

# ── Step 5: Call build_and_train — wrapped in try/except ─────────────────────
print("[harness] Calling build_and_train() ...")
t0 = time.perf_counter()
try:
    model = build_and_train(X_train, y_train, X_val, y_val, class_weights)
    train_time = time.perf_counter() - t0
    print(f"[harness] build_and_train() returned in {{train_time:.2f}}s")
except Exception as exc:
    train_time = time.perf_counter() - t0
    tb = traceback.format_exc()
    print(f"[harness] build_and_train() RAISED:\\n{{tb}}")
    _write_results(_build_error_result(
        f"build_and_train() raised {{type(exc).__name__}}: {{exc}}\\n{{tb}}",
        train_time,
    ))
    sys.exit(1)

if model is None or not hasattr(model, "predict"):
    _write_results(_build_error_result(
        f"build_and_train() returned {{type(model)}} which has no .predict() method",
        train_time,
    ))
    sys.exit(1)

# ── Step 6: Evaluate on VAL set (ONLY) ───────────────────────────────────────
print("[harness] Evaluating on val set ...")
try:
    y_pred = model.predict(X_val)

    val_acc    = float(accuracy_score(y_val, y_pred))
    val_f1     = float(f1_score(y_val, y_pred, average="macro", zero_division=0))
    val_f1_pc  = f1_score(y_val, y_pred, average=None, zero_division=0)
    val_cm     = confusion_matrix(y_val, y_pred).tolist()

    val_f1_per_class = {{
        str(i): float(val_f1_pc[i]) if i < len(val_f1_pc) else 0.0
        for i in range(4)
    }}

    print(f"[harness] val_accuracy  = {{val_acc:.4f}}")
    print(f"[harness] val_f1_macro  = {{val_f1:.4f}}")
    print(f"[harness] val_f1/class  = {{val_f1_per_class}}")

except Exception as exc:
    tb = traceback.format_exc()
    _write_results(_build_error_result(
        f"Evaluation failed: {{exc}}\\n{{tb}}", train_time
    ))
    sys.exit(1)

# ── Step 7: Count model parameters (best-effort) ─────────────────────────────
params = 0
try:
    if hasattr(model, "coef_"):
        params = int(np.prod(model.coef_.shape))
    elif hasattr(model, "n_features_in_"):
        params = int(model.n_features_in_)
    elif hasattr(model, "parameters"):   # PyTorch
        params = sum(p.numel() for p in model.parameters() if p.requires_grad)
except Exception:
    params = 0

# ── Step 8: Write results.json — ALWAYS succeeds if we reach here ─────────────
result = {{
    "exp_id":               EXP_ID,
    "machine_id":           os.environ.get("MACHINE_ID", ""),
    "architecture":         ARCHITECTURE,
    "architecture_family":  ARCHITECTURE_FAMILY,
    "hyperparams":          HYPERPARAMS,
    "timestamp":            TIMESTAMP,
    "val_accuracy":         round(val_acc,  6),
    "val_f1_macro":         round(val_f1,   6),
    "val_f1_per_class":     val_f1_per_class,
    "val_confusion_matrix": val_cm,
    "train_time_seconds":   round(train_time, 3),
    "model_params_count":   params,
    "status":               "success",
    "error_message":        None,
}}

_write_results(result)
print(f"[harness] DONE — val_f1_macro = {{val_f1:.4f}}")

# ── Visualization ──────────────────────────────────────────────
try:
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    import seaborn as sns
    import json as _json
    from pathlib import Path as _Path
    from sklearn.metrics import confusion_matrix as _cm
    from sklearn.metrics import precision_recall_fscore_support as _prf

    _class_names = ['No', 'Low', 'Medium', 'High']
    _plots_dir = _Path(__file__).parent / 'plots'
    _plots_dir.mkdir(exist_ok=True)

    # 1. Confusion matrix
    try:
        _fig, _axes = plt.subplots(1, 2, figsize=(12, 5))
        _cm_raw = _cm(y_val, y_pred)
        _cm_norm = _cm_raw.astype(float) / (_cm_raw.sum(axis=1, keepdims=True) + 1e-9)
        sns.heatmap(_cm_raw, annot=True, fmt='d', ax=_axes[0],
                   xticklabels=_class_names, yticklabels=_class_names, cmap='Blues')
        _axes[0].set_title('Confusion Matrix (raw)')
        sns.heatmap(_cm_norm, annot=True, fmt='.2f', ax=_axes[1],
                   xticklabels=_class_names, yticklabels=_class_names, cmap='Blues')
        _axes[1].set_title(f'Confusion Matrix (normalized) | F1={{val_f1:.4f}}')
        plt.tight_layout()
        plt.savefig(_plots_dir / 'confusion_matrix.png', dpi=150)
        plt.close()
    except Exception as _e:
        print(f'[viz] confusion_matrix failed: {{_e}}')

    # 2. Per-class metrics
    try:
        _p, _r, _f, _ = _prf(y_val, y_pred, labels=[0,1,2,3],
                               average=None, zero_division=0)
        _x = range(len(_class_names))
        _fig, _ax = plt.subplots(figsize=(10, 5))
        _w = 0.25
        _ax.bar([i-_w for i in _x], _p, _w, label='Precision')
        _ax.bar([i    for i in _x], _r, _w, label='Recall')
        _ax.bar([i+_w for i in _x], _f, _w, label='F1')
        _ax.set_xticks(list(_x)); _ax.set_xticklabels(_class_names)
        _ax.set_ylim(0, 1); _ax.legend(); _ax.set_title('Per-Class Metrics')
        plt.tight_layout()
        plt.savefig(_plots_dir / 'per_class_metrics.png', dpi=150)
        plt.close()
    except Exception as _e:
        print(f'[viz] per_class_metrics failed: {{_e}}')

    # 3. Prediction distribution
    try:
        import numpy as _np
        _fig, _axes = plt.subplots(1, 2, figsize=(12, 4))
        _actual_counts = [_np.sum(y_val == i) for i in range(4)]
        _pred_counts   = [_np.sum(y_pred == i) for i in range(4)]
        _axes[0].bar(_class_names, _actual_counts, color='steelblue')
        _axes[0].set_title('Actual Distribution')
        _axes[1].bar(_class_names, _pred_counts, color='coral')
        _axes[1].set_title('Predicted Distribution')
        plt.tight_layout()
        plt.savefig(_plots_dir / 'prediction_distribution.png', dpi=150)
        plt.close()
    except Exception as _e:
        print(f'[viz] prediction_distribution failed: {{_e}}')

    # 4. Leaderboard trend
    try:
        _lb_path = _Path(__file__).parent.parent.parent / 'master_log' / 'leaderboard.json'
        if _lb_path.exists():
            _lb = _json.load(open(_lb_path))
            _exps = _lb.get('experiments', [])
            _f1s  = [e.get('val_f1_macro', 0) for e in _exps]
            _fig, _ax = plt.subplots(figsize=(12, 4))
            _ax.plot(_f1s, marker='o', linewidth=1.5, markersize=4)
            if _f1s:
                _ax.plot(len(_f1s)-1, _f1s[-1], 'ro', markersize=10,
                        label=f'Current: {{_f1s[-1]:.4f}}')
            _ax.set_xlabel('Experiment'); _ax.set_ylabel('F1 Macro')
            _ax.set_title('F1 Trend Across All Experiments')
            _ax.legend(); plt.tight_layout()
            plt.savefig(_plots_dir / 'f1_leaderboard_trend.png', dpi=150)
            plt.close()
    except Exception as _e:
        print(f'[viz] f1_leaderboard_trend failed: {{_e}}')

    # 5. Family comparison
    try:
        if _lb_path.exists():
            _lb = _json.load(open(_lb_path))
            _fam_best = {{}}
            for _e in _lb.get('experiments', []):
                _fam = _e.get('inferred_type', _e.get('architecture_family', 'other'))
                _f1v = _e.get('val_f1_macro', 0)
                if _fam not in _fam_best or _f1v > _fam_best[_fam]:
                    _fam_best[_fam] = _f1v
            _fams = list(_fam_best.keys())
            _vals = [_fam_best[f] for f in _fams]
            _fig, _ax = plt.subplots(figsize=(10, 5))
            _colors = ['red' if f == result.get('inferred_type','') 
                      else 'steelblue' for f in _fams]
            _ax.barh(_fams, _vals, color=_colors)
            _ax.set_xlabel('Best F1 Macro')
            _ax.set_title('Best F1 per Architecture Family')
            plt.tight_layout()
            plt.savefig(_plots_dir / 'family_comparison.png', dpi=150)
            plt.close()
    except Exception as _e:
        print(f'[viz] family_comparison failed: {{_e}}')

    # 6. Feature importance (if available)
    try:
        if hasattr(model, 'feature_importances_'):
            import numpy as _np
            _imp = model.feature_importances_
            _idx = _np.argsort(_imp)[-20:]
            _fig, _ax = plt.subplots(figsize=(10, 8))
            _ax.barh(range(len(_idx)), _imp[_idx])
            _ax.set_title('Top 20 Feature Importances')
            plt.tight_layout()
            plt.savefig(_plots_dir / 'feature_importance.png', dpi=150)
            plt.close()
    except Exception as _e:
        print(f'[viz] feature_importance failed: {{_e}}')

    # 7. Summary 2x2
    try:
        _fig, _axes = plt.subplots(2, 2, figsize=(14, 10))
        # confusion matrix
        _cm_raw = _cm(y_val, y_pred)
        sns.heatmap(_cm_raw, annot=True, fmt='d', ax=_axes[0,0],
                   xticklabels=_class_names, yticklabels=_class_names, cmap='Blues')
        _axes[0,0].set_title('Confusion Matrix')
        # per class metrics
        _p, _r, _f, _ = _prf(y_val, y_pred, labels=[0,1,2,3],
                               average=None, zero_division=0)
        _x = range(4); _w = 0.25
        _axes[0,1].bar([i-_w for i in _x], _p, _w, label='P')
        _axes[0,1].bar([i    for i in _x], _r, _w, label='R')
        _axes[0,1].bar([i+_w for i in _x], _f, _w, label='F1')
        _axes[0,1].set_xticks(list(_x))
        _axes[0,1].set_xticklabels(_class_names)
        _axes[0,1].legend(); _axes[0,1].set_title('Per-Class Metrics')
        # prediction distribution
        _actual_counts = [_np.sum(y_val == i) for i in range(4)]
        _pred_counts   = [_np.sum(y_pred == i) for i in range(4)]
        _x2 = range(4); _w2 = 0.35
        _axes[1,0].bar([i-_w2/2 for i in _x2], _actual_counts, _w2, label='Actual')
        _axes[1,0].bar([i+_w2/2 for i in _x2], _pred_counts,   _w2, label='Predicted')
        _axes[1,0].set_xticks(list(_x2))
        _axes[1,0].set_xticklabels(_class_names)
        _axes[1,0].legend(); _axes[1,0].set_title('Prediction Distribution')
        # leaderboard trend
        if _lb_path.exists():
            _lb  = _json.load(open(_lb_path))
            _f1s = [e.get('val_f1_macro', 0) for e in _lb.get('experiments', [])]
            _axes[1,1].plot(_f1s, marker='o', linewidth=1.5, markersize=3)
            if _f1s:
                _axes[1,1].plot(len(_f1s)-1, _f1s[-1], 'ro', markersize=8)
            _axes[1,1].set_title('F1 Trend')
        _fig.suptitle(f'Experiment Summary | F1={{val_f1:.4f}}', fontsize=14)
        plt.tight_layout()
        plt.savefig(_plots_dir / 'experiment_summary.png', dpi=150)
        plt.close()
    except Exception as _e:
        print(f'[viz] experiment_summary failed: {{_e}}')

    print(f'[viz] plots saved to {{_plots_dir}}')

except Exception as _e:
    print(f'[viz] visualization skipped: {{_e}}')
'''
