"""
agent/core/sandbox.py
────────────────────────────────────────────────────────────────────────────
The Sandboxed Executor ensures that any Python code generated by the agent
is run in a secure, isolated subprocess with strict timeouts.

This prevents the agent from hanging the main orchestrator loop (e.g., if 
a model takes too long to train or loops infinitely).
"""

import os
import sys
import json
import time
import subprocess
from pathlib import Path

# A fixed training script that invokes the agent's model code
# It is executed in a subprocess.
_TRAIN_SCRIPT = '''import sys
import json
import pickle
import time
import traceback
from pathlib import Path
import warnings

# Suppress warnings
warnings.filterwarnings("ignore")

# Extract paths from args
project_root = Path(sys.argv[1])
exp_dir = Path(sys.argv[2])

# Add project root to sys path
sys.path.insert(0, str(project_root))

# Load data
splits_dir = project_root / "data" / "splits"
processed_dir = project_root / "data" / "processed"

try:
    with open(splits_dir / "train.pkl", "rb") as f:
        df_train = pickle.load(f)
        
    with open(splits_dir / "val.pkl", "rb") as f:
        df_val = pickle.load(f)
        
    with open(processed_dir / "class_weights.pkl", "rb") as f:
        class_weights = pickle.load(f)
        
except Exception as e:
    print(json.dumps({"status": "failed", "error": f"Data load error: {e}"}))
    sys.exit(1)

# Import agent's model
model_py = exp_dir / "model.py"
import importlib.util
try:
    spec = importlib.util.spec_from_file_location("model", model_py)
    module = importlib.util.module_from_spec(spec)
    sys.modules["model"] = module
    spec.loader.exec_module(module)
    build_and_train = getattr(module, "build_and_train")
except Exception as e:
    tb = traceback.format_exc()
    print(json.dumps({"status": "failed", "error": f"Import error:\\n{tb}"}))
    sys.exit(1)

# Train
try:
    t0 = time.perf_counter()
    model = build_and_train(df_train, df_val, class_weights)
    train_time = time.perf_counter() - t0
except Exception as e:
    tb = traceback.format_exc()
    print(json.dumps({"status": "failed", "error": f"Training failed:\\n{tb}"}))
    sys.exit(1)
    
if model is None or not hasattr(model, "predict"):
    print(json.dumps({"status": "failed", "error": "Model has no .predict() method"}))
    sys.exit(1)

# Save
try:
    artifacts_dir = exp_dir / "artifacts"
    artifacts_dir.mkdir(exist_ok=True)
    with open(artifacts_dir / "model.pkl", "wb") as f:
        pickle.dump(model, f)
except Exception as e:
    print(json.dumps({"status": "failed", "error": f"Failed to save model: {e}"}))
    sys.exit(1)

print(json.dumps({"status": "success", "train_time": train_time}))
'''

class SandboxedExecutor:
    def __init__(self, project_root: Path):
        self.project_root = Path(project_root)

    def execute_training(self, exp_dir: Path, model_code: str, timeout_seconds: int = 300) -> dict:
        """
        Writes the model_code to exp_dir/model.py and runs the training loop in an isolated subprocess.
        Returns a dict with status and either train_time or error traceback.
        """
        exp_dir = Path(exp_dir)
        exp_dir.mkdir(parents=True, exist_ok=True)
        
        # 1. Write the agent's code
        model_py = exp_dir / "model.py"
        model_py.write_text(model_code, encoding="utf-8")
        
        # 2. Write the fixed trainer script
        trainer_py = exp_dir / "_trainer.py"
        trainer_py.write_text(_TRAIN_SCRIPT, encoding="utf-8")
        
        # 3. Execute subprocess
        try:
            result = subprocess.run(
                [sys.executable, str(trainer_py), str(self.project_root), str(exp_dir)],
                capture_output=True,
                text=True,
                timeout=timeout_seconds
            )
            
            # The trainer prints a JSON response to stdout
            stdout_str = result.stdout.strip()
            
            # Find the last line which should be the JSON
            lines = [l for l in stdout_str.split("\n") if l.strip()]
            if lines:
                try:
                    out_dict = json.loads(lines[-1])
                    return out_dict
                except json.JSONDecodeError:
                    return {
                        "status": "failed",
                        "error": f"Subprocess crashed unexpectedly. Output:\n{stdout_str}\nStderr:\n{result.stderr}"
                    }
            
            if result.returncode != 0:
                return {"status": "failed", "error": f"Process exited with {result.returncode}:\n{result.stderr}"}
                
            return {"status": "failed", "error": "No JSON output found from trainer."}
            
        except subprocess.TimeoutExpired:
            return {"status": "failed", "error": f"Training timed out after {timeout_seconds} seconds."}
        except Exception as e:
            return {"status": "failed", "error": f"Subprocess invocation failed: {e}"}
